name: Deploy to VPS

on:
  push:
    branches: [ your_branch_name ]  # Only run on commits to your specific branch

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v3  

    - name: Connect to VPS
      uses: appleboy/ssh-action@v1  
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull
      run: |
        ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd http-interactions-bot && git pull"

    - name: Restart
      run: |
        ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "pm2 restart 2"
